### PR TITLE
fix(rln): review and refine utility functions in rln

### LINKED ISSUE #279: Review necessity of serialization utility functions
The utility functions in [`rln/src/utils.rs`](https://github.com/vacp2p/zerokit/blob/master/rln/src/utils.rs#L12-L193) are used across various serialization functions, and tests for them exist in [`rln/tests/protocol.rs`](https://github.com/vacp2p/zerokit/blob/8a3e33be418ca6f66fa041c3fda475e24bb82268/rln/tests/protocol.rs#L128). However, it’s unclear whether all of these functions are actually necessary.  

### Tasks:  
- Analyze the usage of each function in `utils.rs` to determine if they are all needed.  
- Check if any functionality is redundant or can be optimized.  
- Consider simplifying or removing unused functions if possible.  

#### Possible but maybe doesn't make sense 
- Benchmark different serialization approaches to compare performance.
- Check with other team members to see what serialization methods they are using and whether these functions align with them.

### Suggested changes 

1.  Update this function regarding current version of RLN. 
https://github.com/vacp2p/zerokit/blob/1930ca1610b85d59909fbbb6936ca042b6ebf1b8/rln/src/protocol.rs#L353

Example: https://github.com/vacp2p/zerokit/blob/1930ca1610b85d59909fbbb6936ca042b6ebf1b8/rln/src/public_api_tests.rs#L696-L706 

2. Use this function inside test to avoid problem with serialisation
 https://github.com/vacp2p/zerokit/blob/1930ca1610b85d59909fbbb6936ca042b6ebf1b8/rln/src/protocol.rs#L371

One of place where need to replace: https://github.com/vacp2p/zerokit/blob/1930ca1610b85d59909fbbb6936ca042b6ebf1b8/rln/src/public_api_tests.rs#L724-L730

----

Related issue: https://github.com/vacp2p/zerokit/issues/21

### PR DESCRIPTION
**Pull request by vinhtc27**
Review and refine utility functions to resolve #279:
- Update utility functions to the current version.
- Remove unused and commented-out code.
- Optimize some utility functions by using extend_from_slice() and pre-allocate size for Vec<u8>.

### CODE REVIEW

File: rln/src/utils.rs [hunk 1]
```diff
@@ -45,77 +47,44 @@ pub fn bytes_le_to_fr(input: &[u8]) -> (Fr, usize) {
...
 
+#[inline(always)]
 pub fn vec_fr_to_bytes_le(input: &[Fr]) -> Result<Vec<u8>> {
-    let mut bytes: Vec<u8> = Vec::new();
-    //We store the vector length
-    bytes.extend(u64::try_from(input.len())?.to_le_bytes().to_vec());
-
-    // We store each element
-    input.iter().for_each(|el| bytes.extend(fr_to_bytes_le(el)));
+    let mut bytes = Vec::with_capacity(8 + input.len() * fr_byte_size());
```
Comment (seemenkina) [inline rln/src/utils.rs:61]: could you please add comment why such size. Just for code readability in the future

File: rln/src/utils.rs [hunk 2]
```diff
@@ -45,77 +47,44 @@ pub fn bytes_le_to_fr(input: &[u8]) -> (Fr, usize) {
...
 pub fn vec_u8_to_bytes_le(input: &[u8]) -> Result<Vec<u8>> {
-    let mut bytes: Vec<u8> = Vec::new();
-    //We store the vector length
-    bytes.extend(u64::try_from(input.len())?.to_le_bytes().to_vec());
-
-    bytes.extend(input);
-
-    Ok(bytes)
-}
+    let mut bytes = Vec::with_capacity(8 + input.len());
```
Comment (seemenkina) [inline rln/src/utils.rs:76]: Same as above

File: rln/src/protocol.rs [hunk 3]
```diff
@@ -100,18 +100,22 @@ pub fn deserialize_identity_tuple(serialized: Vec<u8>) -> (Fr, Fr, Fr, Fr) {
 /// # Errors
 ///
 /// Returns an error if `rln_witness.message_id` is not within `rln_witness.user_message_limit`.
+/// input data is [ identity_secret<32> | user_message_limit<32> | message_id<32> | path_elements[<32>] | identity_path_index<8> | x<32> | external_nullifier<32> ]
 pub fn serialize_witness(rln_witness: &RLNWitnessInput) -> Result<Vec<u8>> {
     message_id_range_check(&rln_witness.message_id, &rln_witness.user_message_limit)?;
 
-    let mut serialized: Vec<u8> = Vec::new();
+    let mut serialized: Vec<u8> = Vec::with_capacity(
+        fr_byte_size() * (5 + rln_witness.path_elements.len())
```
Comment (seemenkina) [inline rln/src/protocol.rs:108]: Also good idea to describe how we calculate length

**Review by seemenkina — COMMENTED** [review]
LGTM, just add a comments near `Vec::with_capacity(...)` on how the length was calculated if there are any numbers in there

**Review by seemenkina — APPROVED** [review]
